name: Build bottles

on: pull_request

env:
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  build-linux-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu16.04:master
    steps:
      - name: Update Homebrew
        run: brew update-reset
      - uses: actions/checkout@master
      - name: Build bottles
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "$GITHUB_WORKSPACE" "$(brew --repo ${{github.repository}})"
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --skip-recursive-dependents --root-url=https://archive.org/download/brewsci/bottles-bio --git-name=Brewsci --git-email=linux@brew.sh
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Upload bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles
  build-macos-bottles:
    runs-on: macos-latest
    env:
      HOMEBREW_FORCE_VENDOR_RUBY: 1
    steps:
      - name: Update Homebrew
        run: brew update-reset
      - uses: actions/checkout@master
      - name: Build bottles
        run: |
          mkdir -p "$(dirname $(brew --repo ${{github.repository}}))"
          cp -a "$GITHUB_WORKSPACE" "$(brew --repo ${{github.repository}})"
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --cleanup --root-url=https://archive.org/download/brewsci/bottles-bio
          cp -a ~/bottles $RUNNER_TEMP/
      - name: Upload bottles
        uses: actions/upload-artifact@v1
        with:
          name: bottles
          path: ${{runner.temp}}/bottles
